include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: true
    - avoid_empty_else: true
    - avoid_relative_lib_imports: true
    - avoid_returning_null_for_future: true
    - avoid_slow_async_io: true
    - avoid_types_as_parameter_names: true
    - cancel_subscriptions: true
    - close_sinks: true
    - control_flow_in_finally: true
    - empty_statements: true
    - no_duplicate_case_values: true
    - prefer_const_constructors: true
    - prefer_const_declarations: true
    - prefer_final_fields: true
    - prefer_final_locals: true
    - sized_box_for_whitespace: true
    - unnecessary_await_in_return: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
