name: painel_admin_margem
description: Painel Admin Margem - A Flutter application for business management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # State management
  get: ^4.6.5
  
  # API
  dio: ^5.3.0
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.0
  
  # Navigation
  go_router: ^10.0.0
  
  # Utils
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  
  # UI
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  mask_text_input_formatter: ^2.5.0
  shimmer: ^3.0.0
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env
